# Project information
site_name: MAGELLAN Schulungsunterlagen
site_description: 'MAGELLAN Schulungsunterlagen'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.magellan-schulungen.stueber.de'

# Copyright
copyright: © 2021 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.magellan-schulungen.de'

# Theming
theme: 
    name: material
    custom_dir: overrides
    language: de
    direction:
    features:
        - navigation.tabs
        - navigation.instant
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Legal links
extra:
  legal:
    - label: Impressum
      link: https://www.stueber.de/imprint.php
    - label: Datenschutz
      link: https://legal.stueber.de/privacy.php

# Customization
extra_css:
    - assets/css/custom.css
    
# Extensions    
markdown_extensions:
    - admonition

# Plugins    
plugins:
    - search
    - img2fig
  
# Navigation  
nav:
- Allgemein: 
  - Überblick: index.md
  - M01 Schulverwaltung:
    - Einstieg: m01/02.einstieg.md
    - Laufbahnprozesse: m01/03.laufbahnprozesse.md
    - Registerkarten: m01/04.registerkarten.md
    - Druck, Dokumente: m01/05.druck.md
  - M02 Zeugniskarte:
      - Landesanpassungen: m02/02.landesanpassungen.md
      - Registerkarte Zeugnis: m02/03.register.zeugnis.md
      - Drucken: m02/04.druck.md
  - M03 Administration:
      - Installation: m03/02.installation.md
      - Lizenz: m03/03.lizenz.md
      - Deinstallation: m03/04.deinstallation.md
      - Update: m03/05.update.md
      - Neue Datenbank: m03/06.neue.db.md
      - Import: m03/07.import.md
      - Benutzerverwaltung: m03/08.benutzer.md
      - Sichern: m03/09.sichern.md
      - MyMAGELLAN CENTER: m03/10.mymag.md
  - M04 Fachwahl und Abitur:
      - Vorbereitung: m04/01.vorbereitungen.md
      - Fachwahl: m04/02.fachwahl.md
      - Abitur: m04/03.abitur.md
  - M05 Bibliothek:
      - Einstieg: m05/01.einstieg.md
      - Mediene und Exmeplare: m05/02.medien_exemplare.md
      - Ausleiher: m05/03.ausleiher.md
      - Vorgänge: m06/04.vorgaenge.md
