# Project information
site_name: MAGELLAN 7 Schulungsunterlagen
site_description: 'MAGELLAN 7 Schulungsunterlagen'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.magellan-schulungen.stueber.de'

# Copyright
copyright: © 2019 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.magellan-schulungen.de'

# Theming
theme: 
    name: null
    custom_dir: 'theme'
    language: de
    direction:
    feature:
        tabs: true
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Customization
extra_css:
    - assets/css/custom.css
    
# Extensions    
markdown_extensions:
    - admonition

# Plugins    
plugins:
    - search
    - img2fig
  
# Navigation  
nav:
- Allgemein: 
    - Überblick: index.md
- M01 MAGELLAN Einführung:
    - Organisatorisches: m01/01.organisatorisches.md
    - Einstieg: m01/02.einstieg.md
    - Laufbahnprozesse: m01/03.laufbahnprozesse.md
    - Registerkarten: m01/04.registerkarten.md
    - Druck, Dokumente: m01/05.druck.md
- M02 MAGELLAN Zeugniskarte:
    - Organisatorisches: m02/01.organisatorisches.md
    - Modul MAGELLAN BERICHTE: m02/02.modul.berichte.md
    - Registerkarte Zeugnis: m02/03.register.zeugnis.md
    - Drucken: m02/04.druck.md
- M03 MAGELLAN Administrator:
    - Organisatorisches: m03/01.organisatorisches.md
    - Installation: m03/02.installation.md
    - Lizenz: m03/03.lizenz.md
    - Deinstallation: m03/04.deinstallation.md
    - Update: m03/05.update.md
    - Neue Datenbank: m03/06.neue.db.md
    - Import: m03/07.import.md
    - Benutzerverwaltung: m03/08.benutzer.md
    - Sichern: m03/09.sichern.md
    - MyMAGELLAN CENTER: m03/10.mymag.md